#!/usr/bin/env python3
"""
Add short definitions to domain names.
"""

import re

# Dictionary of definitions for common terms
DEFINITIONS = {
    # === CORE IR/CS/ML TERMS ===
    'search': 'to look for information in a database or system',
    'vector': 'a mathematical object with magnitude and direction, used in ML and linear algebra',
    'tensor': 'a multidimensional array used in machine learning and physics',
    'matrix': 'a rectangular array of numbers used in mathematics and computer science',
    'index': 'a data structure for fast lookup and retrieval of information',
    'rank': 'to order items by relevance, importance, or quality',
    'query': 'a request for information from a database or search system',
    'parse': 'to analyze and break down into parts',
    'extract': 'to pull out or obtain',
    'filter': 'to remove or separate items',
    'match': 'to correspond or be equal',
    'token': 'a unit or symbol',
    'corpus': 'a collection of texts',
    'cluster': 'a group of similar items',
    'cache': 'a temporary storage for quick access',
    'database': 'an organized collection of data',
    'dataset': 'a collection of data',
    'document': 'a file or record containing information',
    'encode': 'to convert into a coded form',
    'decode': 'to convert from a coded form',
    'research': 'systematic investigation to establish facts or principles',
    'ranker': 'a system or algorithm that orders items by relevance',
    'ranked': 'ordered by relevance, importance, or quality',
    
    # === SCIENTISTS & HISTORICAL FIGURES ===
    'pascal': 'Blaise Pascal, French mathematician and physicist, or the Pascal programming language',
    'newton': 'Isaac Newton, English mathematician and physicist who formulated laws of motion',
    'turing': 'Alan Turing, British mathematician and computer scientist, father of computer science',
    'darwin': 'Charles Darwin, English naturalist who developed theory of evolution',
    'euler': 'Leonhard Euler, Swiss mathematician who made contributions to many fields',
    'gauss': 'Carl Friedrich Gauss, German mathematician known as the prince of mathematicians',
    'einstein': 'Albert Einstein, German physicist who developed theory of relativity',
    'tesla': 'Nikola Tesla, Serbian-American inventor and electrical engineer',
    'planck': 'Max Planck, German physicist who founded quantum theory',
    'bohr': 'Niels Bohr, Danish physicist who contributed to atomic structure',
    'maxwell': 'James Clerk Maxwell, Scottish physicist who formulated electromagnetic theory',
    'edison': 'Thomas Edison, American inventor and businessman',
    'bell': 'Alexander Graham Bell, Scottish inventor of the telephone',
    'watt': 'James Watt, Scottish inventor who improved the steam engine',
    'leibniz': 'Gottfried Leibniz, German mathematician and philosopher',
    'fourier': 'Joseph Fourier, French mathematician known for Fourier analysis',
    'laplace': 'Pierre-Simon Laplace, French mathematician and astronomer',
    'riemann': 'Bernhard Riemann, German mathematician who contributed to geometry and analysis',
    'hilbert': 'David Hilbert, German mathematician known for foundational work',
    'godel': 'Kurt Gödel, Austrian logician and mathematician',
    
    # === SCIENCE TERMS ===
    'field': 'a mathematical structure or a data field in computing',
    'exact': 'precise, accurate, without error',
    'wave': 'a disturbance that transfers energy, or a signal pattern',
    'pure': 'unmixed, uncontaminated, or purely functional in programming',
    'theory': 'a system of ideas explaining observations or phenomena',
    'discover': 'to find or identify something previously unknown',
    'explore': 'to investigate or examine systematically',
    'matter': 'physical substance, or to be of importance',
    'precise': 'exact, accurate, clearly defined',
    'prove': 'to demonstrate truth or validity',
    'force': 'an influence that causes motion or change',
    'mass': 'a measure of the amount of matter',
    'charge': 'an electrical property or to assign responsibility',
    'spin': 'rotation or angular momentum',
    'phase': 'a distinct stage or state',
    'state': 'a condition or mode of being',
    'hypothesis': 'a proposed explanation for observation',
    'experiment': 'a controlled test to verify a hypothesis',
    'observe': 'to watch or notice carefully',
    'measure': 'to determine size, amount, or degree',
    'analyze': 'to examine in detail',
    'test': 'to evaluate or examine',
    'verify': 'to confirm or establish truth',
    'validate': 'to confirm or prove valid',
    'investigate': 'to examine systematically',
    'study': 'to examine or learn about',
    'system': 'a set of connected parts forming a whole',
    'accurate': 'correct, precise, without error',
    'rigorous': 'thorough, precise, exacting',
    'systematic': 'methodical, organized approach',
    'empirical': 'based on observation or experience',
    
    # === COMPUTER SCIENCE TERMS ===
    'algorithm': 'a step-by-step procedure for solving a problem',
    'data': 'facts, figures, or information',
    'structure': 'the arrangement of parts',
    'tree': 'a hierarchical data structure',
    'graph': 'a network of connected nodes',
    'node': 'a point in a network or data structure',
    'edge': 'a connection between nodes',
    'path': 'a route or sequence',
    'queue': 'a first-in-first-out data structure',
    'stack': 'a last-in-first-out data structure',
    'heap': 'a tree-based data structure',
    'hash': 'a function that maps data to a fixed-size value',
    'map': 'a key-value data structure or to transform',
    'set': 'a collection of unique elements',
    'list': 'an ordered collection of items',
    'array': 'an ordered collection of elements',
    'bit': 'a binary digit (0 or 1)',
    'byte': 'a unit of 8 bits',
    'word': 'a unit of data or a sequence of characters',
    'memory': 'storage for data and instructions',
    'register': 'a small high-speed storage location',
    'process': 'a running program instance',
    'thread': 'a lightweight process',
    'task': 'a unit of work',
    'job': 'a unit of work to be executed',
    'pool': 'a collection of resources',
    'buffer': 'temporary storage',
    'stream': 'a sequence of data',
    'compile': 'to convert source code to machine code',
    'execute': 'to run or perform',
    'run': 'to execute or operate',
    'load': 'to read data into memory',
    'save': 'to store data',
    'store': 'to keep data',
    'fetch': 'to retrieve data',
    'read': 'to access data',
    'write': 'to save data',
    'locate': 'to find the position of something',
    'lookup': 'to search for information',
    'sort': 'to arrange in order',
    'join': 'to combine or connect',
    'merge': 'to combine into one',
    'split': 'to divide into parts',
    'slice': 'to cut or extract a portion',
    'transform': 'to change the form or structure',
    'link': 'a connection or reference',
    'fast': 'quick, high-speed',
    'quick': 'rapid, fast',
    'efficient': 'achieving maximum productivity',
    'optimal': 'best possible',
    'scalable': 'able to handle growth',
    'parallel': 'simultaneous execution',
    'concurrent': 'happening at the same time',
    'async': 'asynchronous, not blocking',
    'sync': 'synchronous, blocking',
    'atomic': 'indivisible operation',
    'consistent': 'unchanging, reliable',
    'reliable': 'dependable, trustworthy',
    'robust': 'strong, resilient',
    'secure': 'protected, safe',
    'frame': 'a data structure or time period',
    'series': 'a sequence of values',
    'pipeline': 'a sequence of processing stages',
    'workflow': 'a sequence of tasks',
    'track': 'to monitor or follow',
    'version': 'a specific iteration',
    'reproduce': 'to recreate or duplicate',
    'baseline': 'a reference point',
    'benchmark': 'a standard for comparison',
    'evaluate': 'to assess or judge',
    'compare': 'to examine similarities and differences',
    
    # === MACHINE LEARNING TERMS ===
    'normalize': 'to standardize or adjust to a common scale',
    'optimize': 'to make as effective as possible',
    'train': 'to teach or prepare through practice',
    'learn': 'to gain knowledge or skill',
    'model': 'a representation or simulation',
    'predict': 'to forecast or estimate',
    'classify': 'to categorize or organize',
    'embed': 'to incorporate or represent',
    'infer': 'to deduce or conclude',
    'regress': 'to predict continuous values',
    'standardize': 'to make uniform',
    'scale': 'to adjust size or magnitude',
    'feature': 'a measurable property',
    'label': 'a category or tag',
    'sample': 'a subset of data',
    'batch': 'a group processed together',
    'epoch': 'one complete pass through data',
    'loss': 'a measure of prediction error',
    'error': 'a deviation from correct',
    'metric': 'a standard of measurement',
    'accuracy': 'the degree of correctness',
    'precision': 'the quality of being exact',
    'recall': 'the ability to retrieve information',
    'f1': 'F1 score, harmonic mean of precision and recall',
    'score': 'a numerical rating',
    'gradient': 'the rate of change',
    'minimize': 'to reduce to smallest',
    'maximize': 'to increase to largest',
    'converge': 'to approach a limit',
    'diverge': 'to move apart',
    'neural': 'relating to neural networks',
    'network': 'a system of interconnected nodes',
    'layer': 'a level in a network',
    'weight': 'a parameter in a model',
    'bias': 'a constant term or systematic error',
    'activation': 'a function that determines output',
    'output': 'the result produced',
    'input': 'data fed into a system',
    'hidden': 'not directly observable',
    'deep': 'having many layers',
    'shallow': 'having few layers',
    'wide': 'having many units per layer',
    'narrow': 'having few units per layer',
    'dense': 'fully connected',
    'sparse': 'mostly empty',
    'svm': 'Support Vector Machine, a classification algorithm',
    'knn': 'K-Nearest Neighbors, a classification algorithm',
    'kmeans': 'K-means clustering algorithm',
    'pca': 'Principal Component Analysis, dimensionality reduction',
    'rnn': 'Recurrent Neural Network',
    'cnn': 'Convolutional Neural Network',
    'lstm': 'Long Short-Term Memory network',
    'transformer': 'a neural network architecture',
    'bert': 'Bidirectional Encoder Representations from Transformers',
    'intelligent': 'having ability to learn and reason',
    'adaptive': 'able to adjust to conditions',
    'learned': 'acquired through experience',
    'trained': 'prepared through practice',
    'optimized': 'made as effective as possible',
    'tuned': 'adjusted for optimal performance',
    'training': 'the process of teaching a model',
    'validate': 'to confirm or prove valid',
    'test': 'to evaluate or examine',
    'split': 'to divide into parts',
    'fold': 'a subset in cross-validation',
    'cross': 'validation technique',
    'validation': 'the process of verifying',
    'overfit': 'to memorize training data',
    'underfit': 'to fail to learn patterns',
    'regularize': 'to prevent overfitting',
    'dropout': 'a regularization technique',
    'early': 'premature',
    'stop': 'to halt execution',
    'backprop': 'backpropagation, gradient calculation',
    'forward': 'in the direction of flow',
    'propagate': 'to transmit or spread',
    'descent': 'gradient descent optimization',
    'adam': 'Adaptive Moment Estimation optimizer',
    'sgd': 'Stochastic Gradient Descent',
    'momentum': 'optimization technique',
    'learning': 'the process of acquiring knowledge',
    'rate': 'the speed of change',
    'decay': 'gradual decrease',
    'schedule': 'a plan or timetable',
    'warmup': 'gradual increase',
    'pretrain': 'to train before fine-tuning',
    'finetune': 'to adjust a pre-trained model',
    'transfer': 'to apply knowledge to new domain',
    'domain': 'a specific area or field',
    'adapt': 'to adjust to conditions',
    'fewshot': 'learning from few examples',
    'zero': 'none, nothing',
    'shot': 'an example or attempt',
    'prompt': 'an input instruction',
    'incontext': 'within the context',
    'instruction': 'a command or direction',
    'tune': 'to adjust for optimal performance',
    'data': 'facts, figures, or information',
    'frame': 'a data structure',
    'series': 'a sequence of values',
    'column': 'a vertical data structure',
    'row': 'a horizontal data structure',
    'target': 'the desired outcome',
    'exploratory': 'investigative',
    'analysis': 'detailed examination',
    'eda': 'Exploratory Data Analysis',
    'visualize': 'to create visual representation',
    'plot': 'a graphical representation',
    'chart': 'a visual display',
    'correlate': 'to have mutual relationship',
    'correlation': 'a mutual relationship',
    'covariance': 'a measure of joint variability',
    'variance': 'a measure of spread',
    'std': 'standard deviation',
    'dev': 'deviation',
    'outlier': 'an anomalous data point',
    'anomaly': 'something unusual',
    'detect': 'to discover or identify',
    'clean': 'to remove errors',
    'preprocess': 'to prepare data',
    'impute': 'to estimate missing values',
    'handle': 'to manage or process',
    'missing': 'not present',
    'categorical': 'belonging to categories',
    'numerical': 'consisting of numbers',
    'discrete': 'distinct, separate',
    'continuous': 'uninterrupted',
    'engineer': 'to design or create',
    'selection': 'the act of choosing',
    'reduce': 'to decrease or simplify',
    'dimension': 'a measure of extent',
    'project': 'to map or transform',
    'assess': 'to evaluate',
    'ablate': 'to remove and test effect',
    'hyperparam': 'hyperparameter, a configuration setting',
    'grid': 'a systematic search pattern',
    'random': 'without pattern',
    'bayesian': 'relating to Bayesian statistics',
    'opt': 'optimization',
    'ensemble': 'a combination of models',
    'bag': 'bagging, bootstrap aggregating',
    'boost': 'boosting, sequential improvement',
    'stack': 'stacking, combining models',
    'blend': 'to mix or combine',
    'vote': 'to make a decision',
    'average': 'the mean value',
    
    # === MATH TERMS ===
    'number': 'a mathematical value',
    'digit': 'a single numeral',
    'integer': 'a whole number',
    'real': 'a real number',
    'rational': 'a number expressible as ratio',
    'irrational': 'a number not expressible as ratio',
    'complex': 'a number with real and imaginary parts',
    'prime': 'divisible only by 1 and itself',
    'factor': 'a number that divides another',
    'multiple': 'a product of a number',
    'divisor': 'a number that divides',
    'quotient': 'the result of division',
    'remainder': 'what is left after division',
    'modulo': 'the remainder operation',
    'sum': 'the total',
    'product': 'the result of multiplication',
    'difference': 'the result of subtraction',
    'ratio': 'a comparison of quantities',
    'proportion': 'a relationship between ratios',
    'percent': 'per hundred',
    'fraction': 'a part of a whole',
    'decimal': 'base-10 number system',
    'binary': 'base-2 number system',
    'hex': 'hexadecimal, base-16',
    'octal': 'base-8 number system',
    'base': 'the foundation or radix',
    'exponent': 'a power or index',
    'power': 'exponentiation',
    'root': 'the inverse of exponentiation',
    'square': 'raised to power of 2',
    'cube': 'raised to power of 3',
    'log': 'logarithm',
    'ln': 'natural logarithm',
    'sin': 'sine function',
    'cos': 'cosine function',
    'tan': 'tangent function',
    'angle': 'the space between lines',
    'degree': 'a unit of angle',
    'radian': 'a unit of angle',
    'pi': 'the ratio of circumference to diameter',
    'infinity': 'unbounded quantity',
    'limit': 'a value approached',
    'derivative': 'the rate of change',
    'integral': 'the area under a curve',
    'function': 'a relation between inputs and outputs',
    'variable': 'a symbol representing a value',
    'constant': 'an unchanging value',
    'coefficient': 'a multiplier',
    'term': 'a component of an expression',
    'expression': 'a mathematical phrase',
    'equation': 'a statement of equality',
    'inequality': 'a statement of comparison',
    'solve': 'to find the answer',
    'compute': 'to calculate',
    'calculate': 'to determine mathematically',
    'evaluate': 'to find the value',
    'scalar': 'a single value',
    'dot': 'dot product operation',
    'cross': 'cross product operation',
    'norm': 'a measure of size',
    'magnitude': 'the size or extent',
    'distance': 'a measure of separation',
    'measure': 'to determine size',
    'space': 'a mathematical structure',
    'point': 'a location',
    'line': 'a straight path',
    'plane': 'a flat surface',
    'curve': 'a smooth line',
    'surface': 'a two-dimensional manifold',
    'volume': 'the amount of space',
    'area': 'the size of a surface',
    'perimeter': 'the boundary length',
    'circumference': 'the perimeter of a circle',
    'rigorous': 'thorough, precise',
    'proof': 'a logical demonstration',
    'theorem': 'a proven statement',
    'lemma': 'a supporting theorem',
    'corollary': 'a consequence of a theorem',
    'axiom': 'a self-evident truth',
    'postulate': 'an assumed truth',
    'conjecture': 'an unproven statement',
    'hypothesis': 'a proposed explanation',
    
    # === INFORMATION RETRIEVAL TERMS ===
    'retrieve': 'to get or fetch',
    'find': 'to locate or discover',
    'seek': 'to search for',
    'stem': 'to remove word endings',
    'lemmatize': 'to reduce to base form',
    'order': 'to arrange',
    'arrange': 'to organize',
    'organize': 'to structure',
    'categorize': 'to classify',
    'group': 'to collect together',
    'segment': 'to divide into parts',
    'text': 'written content',
    'term': 'a word or phrase',
    'word': 'a unit of language',
    'phrase': 'a group of words',
    'sentence': 'a complete thought',
    'paragraph': 'a group of sentences',
    'collection': 'a group of items',
    'repository': 'a storage location',
    'archive': 'a collection of records',
    'library': 'a collection of resources',
    'catalog': 'a systematic list',
    'directory': 'an organized listing',
    'registry': 'an official record',
    'store': 'to keep data',
    'map': 'Mean Average Precision metric',
    'ndcg': 'Normalized Discounted Cumulative Gain',
    'mrr': 'Mean Reciprocal Rank',
    'relevance': 'the quality of being pertinent',
    'tfidf': 'Term Frequency-Inverse Document Frequency',
    'bm25': 'Best Matching 25 ranking function',
    'cosine': 'cosine similarity measure',
    'jaccard': 'Jaccard similarity coefficient',
    'euclidean': 'Euclidean distance measure',
    'manhattan': 'Manhattan distance measure',
    'hamming': 'Hamming distance measure',
    'levenshtein': 'Levenshtein edit distance',
    'edit': 'to modify or change',
    'dissimilarity': 'the state of being different',
    'embedding': 'a vector representation',
    'semantic': 'relating to meaning',
    'syntactic': 'relating to structure',
    'lexical': 'relating to words',
    'relevant': 'pertinent, applicable',
    'comprehensive': 'complete, thorough',
    'complete': 'entire, whole',
    'exhaustive': 'thorough, complete',
    'thorough': 'complete, detailed',
    'scan': 'to examine quickly',
    'browse': 'to look through',
    'navigate': 'to move through',
    'traverse': 'to travel across',
    'iterate': 'to repeat',
    'enumerate': 'to list',
    'aggregate': 'to collect together',
    'union': 'a combination of sets',
    'intersect': 'to overlap',
    'diff': 'difference operation',
    'subtract': 'to remove',
    'reduce': 'to decrease or simplify',
    'fold': 'to combine',
    'unfold': 'to expand',
    'flatten': 'to make flat',
    'nest': 'to embed',
    'compress': 'to reduce size',
    'decompress': 'to restore size',
    'serialize': 'to convert to format',
    'deserialize': 'to convert from format',
    'digest': 'a summary or hash',
    'checksum': 'a verification value',
    'fingerprint': 'a unique identifier',
    'signature': 'a distinctive mark',
    'prefix': 'a beginning part',
    'suffix': 'an ending part',
    'substring': 'a part of a string',
    'subsequence': 'a part of a sequence',
    'ngram': 'a sequence of n items',
    'bigram': 'a sequence of 2 items',
    'trigram': 'a sequence of 3 items',
    'inverted': 'reversed index structure',
    'forward': 'in the direction ahead',
    'backward': 'in reverse direction',
    'bidirectional': 'in both directions',
    'multilingual': 'supporting multiple languages',
    'ranking': 'the process of ordering',
    'scoring': 'the process of rating',
    'weighting': 'the process of assigning importance',
    'boosting': 'increasing importance',
    'penalizing': 'decreasing importance',
    'rerank': 'to rank again',
    'refine': 'to improve',
    'calibrate': 'to adjust',
    'adjust': 'to modify',
    'retrieval': 'the act of retrieving',
    
    # === SCALE TERMS ===
    'big': 'large in size',
    'large': 'of considerable size',
    'vast': 'very large',
    'huge': 'extremely large',
    'massive': 'very large and heavy',
    'immense': 'extremely large',
    'enormous': 'very large',
    'giant': 'exceptionally large',
    'mega': 'very large, million',
    'macro': 'large-scale',
    'grand': 'impressive in size',
    'major': 'greater in importance or size',
    'max': 'maximum, the greatest',
    'peak': 'the highest point',
    'summit': 'the top or highest point',
    'apex': 'the highest point',
    'zenith': 'the highest point',
    'titan': 'a person of great size or strength',
    'colossal': 'extremely large',
    'towering': 'very tall',
    'monumental': 'very large and impressive',
    'mighty': 'very powerful',
    'powerful': 'having great strength',
    'deep': 'extending far down',
    'profound': 'very deep or intense',
    'bottomless': 'having no bottom',
    'abyss': 'a deep void',
    'core': 'the central part',
    'center': 'the middle point',
    'heart': 'the central or vital part',
    'essence': 'the fundamental nature',
    'root': 'the fundamental part',
    'base': 'the foundation',
    'foundation': 'the base or support',
    'bedrock': 'the solid foundation',
    'depths': 'the deep parts',
    'wide': 'having great breadth',
    'broad': 'having great width',
    'expansive': 'covering a large area',
    'extensive': 'covering a large area',
    'full': 'complete, entire',
    'span': 'the extent or reach',
    'reach': 'the extent of influence',
    'range': 'the extent of variation',
    'scope': 'the extent of coverage',
    'extent': 'the degree or range',
    'scale': 'the size or magnitude',
    'high': 'elevated, tall',
    'tall': 'of great height',
    'elevated': 'raised up',
    'lofty': 'very high',
    'sky': 'the upper atmosphere',
    'cloud': 'a visible mass of water vapor',
    'pinnacle': 'the highest point',
    'crest': 'the top of a wave or hill',
    'ridge': 'a long narrow elevation',
    'height': 'the measurement upward',
    'infinite': 'without limit',
    'endless': 'having no end',
    'boundless': 'without boundaries',
    'limitless': 'without limits',
    'eternal': 'lasting forever',
    'perpetual': 'never ending',
    'unlimited': 'without restrictions',
    'unbounded': 'without boundaries',
    'immeasurable': 'too large to measure',
    'incalculable': 'too large to calculate',
    'volume': 'the amount of space',
    'capacity': 'the maximum amount',
    'bulk': 'large mass',
    'mass': 'a large body of matter',
    'weight': 'the force of gravity',
    'density': 'mass per unit volume',
    'breadth': 'the width or extent',
    'width': 'the measurement across',
    'depth': 'the measurement downward',
    'length': 'the measurement along',
    'dimension': 'a measure of extent',
    'measure': 'to determine size',
}

def get_definition(name: str) -> str:
    """Get definition for a domain name."""
    name_lower = name.lower()
    
    # Direct lookup
    if name_lower in DEFINITIONS:
        return DEFINITIONS[name_lower]
    
    # Check for common suffixes and try base word
    suffixes = ['er', 'or', 'ed', 'ing', 'ion', 'ive', 'al', 'ic', 'ous', 'est', 'ly']
    for suffix in suffixes:
        if name_lower.endswith(suffix):
            base = name_lower[:-len(suffix)]
            if base in DEFINITIONS:
                base_def = DEFINITIONS[base]
                return f'variant of {base}, {base_def}'
    
    # Check for compound words (two words combined)
    # Try to split at common boundaries
    for i in range(3, len(name_lower) - 2):
        part1 = name_lower[:i]
        part2 = name_lower[i:]
        if part1 in DEFINITIONS and part2 in DEFINITIONS:
            def1 = DEFINITIONS[part1]
            def2 = DEFINITIONS[part2]
            return f'combines {part1} ({def1}) and {part2} ({def2})'
    
    # No definition found
    return ''
